import { Subscription, Invoice } from './types';
import { buildParentLoginId, extractFirstName } from './utils/parent-login-id';

function seedLoginId(studentName: string, suffix: string): string {
  return buildParentLoginId(extractFirstName(studentName), suffix);
}

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'INV-3829-K',
    studentName: 'Liam Sterling',
    parentName: 'Marcus Sterling',
    parentEmail: 'm.sterling@footballmail.com',
    amount: 450,
    courseName: 'Striker Masterclass: Elite Finishing',
    date: '2026-06-01',
    dueDate: '2026-06-15',
    status: 'Success',
    transactionId: 'TXN-9842-AF',
    semester: 'Summer 2026'
  },
  {
    id: 'INV-4021-M',
    studentName: 'Elena Bellingham',
    parentName: 'Benicio Bellingham',
    parentEmail: 'b.bellingham@pro-striker.com',
    amount: 280,
    courseName: 'Midfield Maestro: Tactical Passing',
    date: '2026-06-05',
    dueDate: '2026-06-20',
    status: 'Success',
    transactionId: 'TXN-1049-DD',
    semester: 'Summer 2026'
  },
  {
    id: 'INV-7291-B',
    studentName: 'Christian Kane',
    parentName: 'Christopher Kane',
    parentEmail: 'kane@synco-sports.com',
    amount: 520,
    courseName: 'Goalkeeping Advanced: Shot Stopping & Reflexes',
    date: '2026-06-10',
    dueDate: '2026-06-25',
    status: 'Failed',
    semester: 'Summer 2026'
  },
  {
    id: 'INV-8210-C',
    studentName: 'Mia Grealish',
    parentName: 'Greta Grealish',
    parentEmail: 'greta@grealish-sports.com',
    amount: 320,
    courseName: 'Defensive Wall: Backline Strategy & Positioning',
    date: '2026-06-12',
    dueDate: '2026-06-27',
    status: 'Pending',
    semester: 'Summer 2026'
  },
  {
    id: 'INV-1902-S',
    studentName: 'Sophia Cruyff',
    parentName: 'Roman Cruyff',
    parentEmail: 'roman.c@cruyff-academy.com',
    amount: 300,
    courseName: 'Pro Fitness & Conditioning: Speed & Agility',
    date: '2026-06-15',
    dueDate: '2026-06-30',
    status: 'Success',
    transactionId: 'TXN-4902-ZC',
    semester: 'Summer 2026'
  },
  {
    id: 'INV-9081-N',
    studentName: 'Liam Sterling',
    parentName: 'Marcus Sterling',
    parentEmail: 'm.sterling@footballmail.com',
    amount: 450,
    courseName: 'Striker Masterclass: Elite Finishing',
    date: '2026-07-01',
    dueDate: '2026-07-15',
    status: 'Pending',
    semester: 'Summer 2026'
  },
  {
    id: 'INV-3029-T',
    studentName: 'Christian Kane',
    parentName: 'Christopher Kane',
    parentEmail: 'kane@synco-sports.com',
    amount: 520,
    courseName: 'Goalkeeping Advanced: Shot Stopping & Reflexes',
    date: '2026-05-10',
    dueDate: '2026-05-25',
    status: 'Success',
    transactionId: 'TXN-3829-NN',
    semester: 'Summer 2026'
  },
  {
    id: 'INV-8371-G',
    studentName: 'Sophia Cruyff',
    parentName: 'Roman Cruyff',
    parentEmail: 'roman.c@cruyff-academy.com',
    amount: 300,
    courseName: 'Pro Fitness & Conditioning: Speed & Agility',
    date: '2026-07-01',
    dueDate: '2026-07-15',
    status: 'Failed',
    semester: 'Summer 2026'
  }
];

export const INITIAL_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'SUB-1002-V',
    studentName: 'Liam Sterling',
    parentName: 'Marcus Sterling',
    parentEmail: 'm.sterling@footballmail.com',
    courseName: 'Striker Masterclass: Elite Finishing',
    status: 'Active',
    tier: 'Premium',
    monthlyFee: 450,
    nextBillingDate: '2026-07-15',
    batch: 'Elite Pro Squad',
    age: 14,
    height: 165,
    weight: 54,
    aadhaar: '5544-2233-9900',
    education: 'Oakridge International - 9th Grade',
    familyDetails: 'Father: Head Coach, Mother: Pediatrician',
    profilePic: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    parentLoginId: seedLoginId('Liam Sterling', '48291'),
  },
  {
    id: 'SUB-2031-D',
    studentName: 'Elena Bellingham',
    parentName: 'Benicio Bellingham',
    parentEmail: 'b.bellingham@pro-striker.com',
    courseName: 'Midfield Maestro: Tactical Passing',
    status: 'Active',
    tier: 'Standard',
    monthlyFee: 280,
    nextBillingDate: '2026-07-20',
    batch: 'Under-15 Development Group',
    age: 13,
    height: 158,
    weight: 48,
    aadhaar: '7788-3322-1100',
    education: 'St. Mary\'s Secondary School - 8th Grade',
    familyDetails: 'Father: Sports Analyst, Mother: Banker',
    profilePic: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    parentLoginId: seedLoginId('Elena Bellingham', '52341'),
  },
  {
    id: 'SUB-3092-N',
    studentName: 'Christian Kane',
    parentName: 'Christopher Kane',
    parentEmail: 'kane@synco-sports.com',
    courseName: 'Goalkeeping Advanced: Shot Stopping & Reflexes',
    status: 'Paused',
    tier: 'Premium',
    monthlyFee: 520,
    nextBillingDate: '2026-07-25',
    batch: 'Weekend Advanced Training',
    age: 15,
    height: 178,
    weight: 68,
    aadhaar: '1122-3344-5566',
    education: 'Metropolis High School - 10th Grade',
    familyDetails: 'Father: Logistics Director, Mother: Architect',
    profilePic: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    parentLoginId: seedLoginId('Christian Kane', '38472'),
  },
  {
    id: 'SUB-4081-G',
    studentName: 'Mia Grealish',
    parentName: 'Greta Grealish',
    parentEmail: 'greta@grealish-sports.com',
    courseName: 'Defensive Wall: Backline Strategy & Positioning',
    status: 'Active',
    tier: 'Standard',
    monthlyFee: 320,
    nextBillingDate: '2026-07-27',
    batch: 'Under-12 Elite Squad',
    age: 11,
    height: 145,
    weight: 38,
    aadhaar: '9900-8877-6655',
    education: 'Greenwood Elementary - 6th Grade',
    familyDetails: 'Single Mother: Marketing Director',
    profilePic: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    parentLoginId: seedLoginId('Mia Grealish', '61829'),
  },
  {
    id: 'SUB-5012-C',
    studentName: 'Sophia Cruyff',
    parentName: 'Roman Cruyff',
    parentEmail: 'roman.c@cruyff-academy.com',
    courseName: 'Pro Fitness & Conditioning: Speed & Agility',
    status: 'Active',
    tier: 'Standard',
    monthlyFee: 300,
    nextBillingDate: '2026-07-15',
    batch: 'Under-15 Development Group',
    age: 12,
    height: 152,
    weight: 42,
    aadhaar: '4455-6677-8899',
    education: 'The Heritage Academy - 7th Grade',
    familyDetails: 'Father: Academy Director, Mother: Artist',
    profilePic: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    parentLoginId: seedLoginId('Sophia Cruyff', '73516'),
  }
];
